name: presdio_pii
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_markdown: ^0.7.7+1
  http: ^1.5.0
  intl: ^0.20.2
  sqflite: ^2.3.0
  path: ^1.8.3
  sqflite_common_ffi: ^2.3.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
